on: 
  push:
    branches:
      - main
jobs: 
  bench:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: echo ${{secrets.PAT}} | gh auth login --with-token
      - run: gh auth setup-git
      - run: git config user.name ${{github.actor}}
      - run: git config user.email ${{secrets.email}}
      
      - run: choco install zig
      - run: zig version
      - run: zig build --release=fast
      
      - run: Write-Host "${{github.sha}}:`n`t56@1:`t" -NoNewLine 6>> ${{runner.temp}}/results.txt
      - name: Run 56@2
        run: (Measure-Command {./zig-out/bin/out.exe 56 2 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: Write-Host "`t80@1:`t" -NoNewLine 6>> ${{runner.temp}}/results.txt
      - name: Run 80@3
        run: (Measure-Command {./zig-out/bin/out.exe 80 3 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: Write-Host "`t120@4:`t" -NoNewLine 6>> ${{runner.temp}}/results.txt
      - name: Run 120@4
        run: (Measure-Command {./zig-out/bin/out.exe 120 4 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: Write-Host "`t180@4:`t" -NoNewLine 6>> ${{runner.temp}}/results.txt
      - name: Run 160@4
        run: (Measure-Command {./zig-out/bin/out.exe 160 4 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: Write-Host "`n" -NoNewLine 6>> ${{runner.temp}}/results.txt

      - uses: actions/checkout@v4
        with:
          ref: 'results'
          token: ${{secrets.PAT}}
      - run: cat ${{runner.temp}}/results.txt >> ./results.txt
      - run: git add ./results.txt
      - run: git commit -m "commit ${{github.sha}} at $((Get-Date).ToString())"
      - run: git push
