on: 
  push:
    branches:
      - main
jobs: 
  bench:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - run: git config user.name ${{github.actor}}
      - run: git config user.email ${{secrets.email}}
      
      - run: zig version
      - run: zig build --release=fast
      
      - run: echo -en "${{github.sha}}:\n\t56@2:\t" >> ${{runner.temp}}/results.txt
      - name: Run 56@2
        run: env time -f "%e sec" -ao ${{runner.temp}}/results.txt ./zig-out/bin/out 56 2
      - run: echo -en "\t80@3:\t" >> ${{runner.temp}}/results.txt
      - name: Run 80@3
        run: env time -f "%e sec" -ao ${{runner.temp}}/results.txt ./zig-out/bin/out 80 3
      - run: echo -en "\t120@8:\t" >> ${{runner.temp}}/results.txt
      - name: Run 120@8
        run: env time -f "%e sec" -ao ${{runner.temp}}/results.txt ./zig-out/bin/out 120 8
      - run: echo -en "\t180@4:\t" >> ${{runner.temp}}/results.txt
      - name: Run 160@max
        run: env time -f "%e sec" -ao ${{runner.temp}}/results.txt ./zig-out/bin/out 160 0
      - run: echo -en "\n" >> ${{runner.temp}}/results.txt

      - uses: actions/checkout@v4
        with:
          ref: 'results'
          token: ${{secrets.PAT}}
      - run: cat ${{runner.temp}}/results.txt >> ./results.txt
      - run: git add ./results.txt
      - run: git commit -m "commit ${{github.sha}} at $(date)"
      - run: git push
