on: [push]
jobs: 
  bench:
    runs-on: windows-latest
    steps:
      - run: choco install zig
      - run: zig version
      
      - uses: actions/checkout@v4
      
      - name: run56@1
        run: zig build run --release=fast -- 56 1
      - name: run80@1
        run: zig build run --release=fast -- 80 1
      - name: run120@6
        run: zig build run --release=fast -- 120 2
      - name: run180@16
        run: zig build run --release=fast -- 180 4
