on: 
  push:
    branches:
      - main
jobs: 
  bench:
    runs-on: windows-latest
    steps:
      - run: echo ${{secrets.PAT}} | gh auth login --with-token
      - run: gh auth setup-git
      - run: choco install zig
      - run: zig version
      
      - uses: actions/checkout@v4
      - run: zig build --release=fast
      
      - run: echo "${{github.sha}}:`n`t56@1:`t" >> ${{runner.temp}}/results.txt
      - name: Run 56@2
        run: (Measure-Command {./zig-out/bin/out.exe 56 2 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: echo "`t80@1:`t"
      - name: Run 80@3
        run: (Measure-Command {./zig-out/bin/out.exe 80 3 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: echo "`t120@4:`t"
      - name: Run 120@4
        run: (Measure-Command {./zig-out/bin/out.exe 120 4 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      - run: echo "`t180@4:`t"
      #- name: Run 160@4
      #  run: (Measure-Command {./zig-out/bin/out.exe 160 4 | Out-Default}).ToString() >> ${{runner.temp}}/results.txt
      #- run: echo "`n" >> ${{runner.temp}}/results.txt

      - uses: actions/checkout@v4
        with:
          ref: 'results'
      - run: cat ${{runner.temp}}/results.txt >> ./results.txt
      - run: git add ./results.txt
      - run: $time = Get-Date -Format "commit ${{github.sha}} at dd-MM-yyyy HH:mm:ss"
      - run: git commit -m "$time"
      - run: git push
